### ISSUE TITLE
GitHub workflow is supposed to build the docker image on merges to master but is not.

### ISSUE THREAD

**Issue by AtomicMegaNerd** [AtomicMegaNerd/pinyin_tone_marks#4]
Not sure why this isn't working yet:

```yaml
 push_to_registry:
    name: Push Docker image to GitHub Packages
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/head/master' }}
```

I want to troubleshoot this and have the docker image build only on merges to master.
